# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Cimos.etchy
PackageVersion: 0.1.1
InstallerType: wix
Scope: machine
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Commands:
  - etchy
  - etchy-gui
ReleaseDate: 2026-10-03
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Cimos/etchy/releases/download/v0.1.1/etchy-viewer-v0.1.1-windows-x86_64.msi
    InstallerSha256: 4EEBC420D4807E293E7676F793C96F8D420B93A74ABEC005C5D8D055A2FFBD65
    ProductCode: '{A48CA0BC-A4CC-4738-8BE8-CDAF7E83D28A}'
    AppsAndFeaturesEntries:
      - UpgradeCode: '{797C2D6C-50FA-5F24-8BDB-AAC25C2C80BE}'
ManifestType: installer
ManifestVersion: 1.12.0
